language: python

python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

sudo: required

# safelist
branches:
  only:
  - master
  - development

cache: pip
install:
  - pip install -r requirements.txt

services:
  - docker

script:
  - docker build -t oduwsdl/fch:test .
  - docker run oduwsdl/fch:test m_nsiddique

after_script:
  - docker tag oduwsdl/fch:test oduwsdl/fch:test 
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: bash testing.sh
  on:
    branch: development

